name: record_ios
description: iOS implementation for record package called by record_platform_interface.
version: 10.0.1
homepage: https://github.com/llfbandit/record/tree/master/record_ios

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface/

flutter:
  plugin:
    implements: record
    platforms:
      ios:
        pluginClass: RecordIosPlugin
