name: record_web
description: Web specific implementation for record package called by record_platform_interface.
version: 1.2.0
homepage: https://github.com/llfbandit/record/tree/master/record_web

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  web: ^1.0.0
  record_platform_interface:
    path: ../record_platform_interface/

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RecordPluginWeb
        fileName: 'record_web.dart'
  
  assets:
    - assets/js/record.worklet.js
    - assets/js/record.fixwebmduration.js
