name: record
description: Audio recorder from microphone to file or stream with multiple codecs, bit rate and sampling rate options.
version: 10.0.1
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface:
    path: ../record_platform_interface/
  record_web:
    path: ../record_web/
  record_windows:
    path: ../record_windows/
  record_linux:
    path: ../record_linux/
  record_android:
    path: ../record_android/
  record_ios:
    path: ../record_ios/
  record_macos:
    path: ../record_macos/

dev_dependencies:
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_ios
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_macos
      linux:
        default_package: record_linux
