name: record_macos
description: macOS implementation for record package called by record_platform_interface.
version: 1.1.1
homepage: https://github.com/llfbandit/record/tree/master/record_macos

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface/

flutter:
  plugin:
    implements: record
    platforms:
      macos:
        pluginClass: RecordMacOsPlugin
